title: Portfolio de juanma-cc
description: Mi portfolio (en construcción)
#theme: minimal
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
