title: Portfolio de @juanma-cc
description: Este es mi portfolio personal donde recopilo proyectos y conocimientos sobre ciberseguridad.
show_downloads: false
show_git: false
google_analytics: G-YCE622JG2H
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-hacker